apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-server
  namespace: couple-{{ .Values.coupleId }}
spec:
  type: LoadBalancer        # <--- Change this from ClusterIP
  selector:
    app: relmonition
    tenant: {{ .Values.coupleId | quote }}
  ports:
    - protocol: TCP
      port: 80              # <--- It's standard to use 80 for public URLs
      targetPort: 3001