apiVersion: apps/v1
kind: Deployment
metadata:
  name: relmonition-server
  labels:
    app: relmonition
spec:
  replicas: 2
  selector:
    matchLabels:
      app: relmonition
  template:
    metadata:
      labels:
        app: relmonition
    spec:
      containers:
      - name: server
        image: relmonition-server:latest # This will be pushed by Jenkins
        ports:
        - containerPort: 3001
        env:
        - name: TURSO_CONNECTION_URL
          valueFrom:
            secretKeyRef:
              name: tenant-secrets
              key: db-url
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
